"""empty message

Revision ID: 5925767b94c2
Revises: 2bdde7da2eac
Create Date: 2020-02-01 10:35:35.042758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5925767b94c2'
down_revision = '2bdde7da2eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
